//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int IDTable { get; set; }
        public int IDProduct { get; set; }
        public string Product { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Modified_date { get; set; }
    }
}
